package com.transportsmr.app.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.transportsmr.app.model.Stop;

import com.transportsmr.app.model.StopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stopDaoConfig;

    private final StopDao stopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stopDaoConfig = daoConfigMap.get(StopDao.class).clone();
        stopDaoConfig.initIdentityScope(type);

        stopDao = new StopDao(stopDaoConfig, this);

        registerDao(Stop.class, stopDao);
    }
    
    public void clear() {
        stopDaoConfig.clearIdentityScope();
    }

    public StopDao getStopDao() {
        return stopDao;
    }

}
