package com.transportsmr.app.model;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ROUTE".
 */
@Root(name = "route", strict = false)
@Entity
public class Route {
    @Id
    private Long id;
    @Element(name = "KR_ID")
    private String kr_id;
    @Element
    private String number;
    @Element(required = false)
    private String transportType;
    @Element(required = false)
    private String affiliationID;
    @Element(required = false)
    private String affiliation;

    @Generated(hash = 467763370)
    public Route() {
    }

    public Route(Long id) {
        this.id = id;
    }

    @Generated(hash = 665048472)
    public Route(Long id, String kr_id, String number, String transportType, String affiliationID, String affiliation) {
        this.id = id;
        this.kr_id = kr_id;
        this.number = number;
        this.transportType = transportType;
        this.affiliationID = affiliationID;
        this.affiliation = affiliation;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKr_id() {
        return kr_id;
    }

    public void setKr_id(String kr_id) {
        this.kr_id = kr_id;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getTransportType() {
        return transportType;
    }

    public void setTransportType(String transportType) {
        this.transportType = transportType;
    }

    public String getAffiliationID() {
        return affiliationID;
    }

    public void setAffiliationID(String affiliationID) {
        this.affiliationID = affiliationID;
    }

    public String getAffiliation() {
        return affiliation;
    }

    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation;
    }

}
