package com.transportsmr.app.model;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STOP".
 */
@Root(name = "stop", strict = false)
@Entity
public class Stop {

    @Id
    private Long id;
    @Element(name = "KS_ID")
    private String ks_id;
    @Element
    private String title;
    private String title_lc;
    @Element(required = false)
    private String adjacentStreet;
    private String adjacentStreet_lc;
    @Element(required = false)
    private String direction;
    @Element(required = false)
    private String cluster;
    @Element(required = false)
    private String busesMunicipal;
    @Element(required = false)
    private String busesCommercial;
    @Element(required = false)
    private String busesPrigorod;
    @Element(required = false)
    private String busesSeason;
    @Element(required = false)
    private String busesSpecial;
    @Element(required = false)
    private String trams;
    @Element(required = false)
    private String trolleybuses;
    @Element(required = false)
    private String metros;
    @Element(required = false)
    private String infotabloExists;
    @Element(required = false)
    private Float latitude;
    @Element(required = false)
    private Float longitude;
    @Element(required = false)
    private Boolean favorite;

    @Generated(hash = 362110707)
    public Stop() {
    }

    public Stop(Long id) {
        this.id = id;
    }

    @Generated(hash = 1645264370)
    public Stop(Long id, String ks_id, String title, String title_lc, String adjacentStreet, String adjacentStreet_lc, String direction, String cluster, String busesMunicipal, String busesCommercial, String busesPrigorod, String busesSeason, String busesSpecial, String trams, String trolleybuses, String metros, String infotabloExists, Float latitude, Float longitude, Boolean favorite) {
        this.id = id;
        this.ks_id = ks_id;
        this.title = title;
        this.title_lc = title_lc;
        this.adjacentStreet = adjacentStreet;
        this.adjacentStreet_lc = adjacentStreet_lc;
        this.direction = direction;
        this.cluster = cluster;
        this.busesMunicipal = busesMunicipal;
        this.busesCommercial = busesCommercial;
        this.busesPrigorod = busesPrigorod;
        this.busesSeason = busesSeason;
        this.busesSpecial = busesSpecial;
        this.trams = trams;
        this.trolleybuses = trolleybuses;
        this.metros = metros;
        this.infotabloExists = infotabloExists;
        this.latitude = latitude;
        this.longitude = longitude;
        this.favorite = favorite;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKs_id() {
        return ks_id;
    }

    public void setKs_id(String ks_id) {
        this.ks_id = ks_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle_lc() {
        return title_lc;
    }

    public void setTitle_lc(String title_lc) {
        this.title_lc = title_lc;
    }

    public String getAdjacentStreet() {
        return adjacentStreet;
    }

    public void setAdjacentStreet(String adjacentStreet) {
        this.adjacentStreet = adjacentStreet;
    }

    public String getAdjacentStreet_lc() {
        return adjacentStreet_lc;
    }

    public void setAdjacentStreet_lc(String adjacentStreet_lc) {
        this.adjacentStreet_lc = adjacentStreet_lc;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getCluster() {
        return cluster;
    }

    public void setCluster(String cluster) {
        this.cluster = cluster;
    }

    public String getBusesMunicipal() {
        return busesMunicipal;
    }

    public void setBusesMunicipal(String busesMunicipal) {
        this.busesMunicipal = busesMunicipal;
    }

    public String getBusesCommercial() {
        return busesCommercial;
    }

    public void setBusesCommercial(String busesCommercial) {
        this.busesCommercial = busesCommercial;
    }

    public String getBusesPrigorod() {
        return busesPrigorod;
    }

    public void setBusesPrigorod(String busesPrigorod) {
        this.busesPrigorod = busesPrigorod;
    }

    public String getBusesSeason() {
        return busesSeason;
    }

    public void setBusesSeason(String busesSeason) {
        this.busesSeason = busesSeason;
    }

    public String getBusesSpecial() {
        return busesSpecial;
    }

    public void setBusesSpecial(String busesSpecial) {
        this.busesSpecial = busesSpecial;
    }

    public String getTrams() {
        return trams;
    }

    public void setTrams(String trams) {
        this.trams = trams;
    }

    public String getTrolleybuses() {
        return trolleybuses;
    }

    public void setTrolleybuses(String trolleybuses) {
        this.trolleybuses = trolleybuses;
    }

    public String getMetros() {
        return metros;
    }

    public void setMetros(String metros) {
        this.metros = metros;
    }

    public String getInfotabloExists() {
        return infotabloExists;
    }

    public void setInfotabloExists(String infotabloExists) {
        this.infotabloExists = infotabloExists;
    }

    public Float getLatitude() {
        return latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    public Float getLongitude() {
        return longitude;
    }

    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

}
