package com.transportsmr.app.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STOP".
 */
@Entity
public class Stop {

    @Id
    private Long id;
    private String ks_id;
    private String title;
    private String adjacentStreet;
    private String direction;
    private String cluster;
    private String busesMunicipal;
    private String busesCommercial;
    private String busesPrigorod;
    private String busesSeason;
    private String busesSpecial;
    private String trams;
    private String trolleybuses;
    private String metros;
    private String infotabloExists;
    private Float latitude;
    private Float longitude;

    @Generated(hash = 362110707)
    public Stop() {
    }

    public Stop(Long id) {
        this.id = id;
    }

    @Generated(hash = 1670359702)
    public Stop(Long id, String ks_id, String title, String adjacentStreet, String direction, String cluster, String busesMunicipal, String busesCommercial, String busesPrigorod, String busesSeason, String busesSpecial, String trams, String trolleybuses, String metros, String infotabloExists, Float latitude, Float longitude) {
        this.id = id;
        this.ks_id = ks_id;
        this.title = title;
        this.adjacentStreet = adjacentStreet;
        this.direction = direction;
        this.cluster = cluster;
        this.busesMunicipal = busesMunicipal;
        this.busesCommercial = busesCommercial;
        this.busesPrigorod = busesPrigorod;
        this.busesSeason = busesSeason;
        this.busesSpecial = busesSpecial;
        this.trams = trams;
        this.trolleybuses = trolleybuses;
        this.metros = metros;
        this.infotabloExists = infotabloExists;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKs_id() {
        return ks_id;
    }

    public void setKs_id(String ks_id) {
        this.ks_id = ks_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAdjacentStreet() {
        return adjacentStreet;
    }

    public void setAdjacentStreet(String adjacentStreet) {
        this.adjacentStreet = adjacentStreet;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getCluster() {
        return cluster;
    }

    public void setCluster(String cluster) {
        this.cluster = cluster;
    }

    public String getBusesMunicipal() {
        return busesMunicipal;
    }

    public void setBusesMunicipal(String busesMunicipal) {
        this.busesMunicipal = busesMunicipal;
    }

    public String getBusesCommercial() {
        return busesCommercial;
    }

    public void setBusesCommercial(String busesCommercial) {
        this.busesCommercial = busesCommercial;
    }

    public String getBusesPrigorod() {
        return busesPrigorod;
    }

    public void setBusesPrigorod(String busesPrigorod) {
        this.busesPrigorod = busesPrigorod;
    }

    public String getBusesSeason() {
        return busesSeason;
    }

    public void setBusesSeason(String busesSeason) {
        this.busesSeason = busesSeason;
    }

    public String getBusesSpecial() {
        return busesSpecial;
    }

    public void setBusesSpecial(String busesSpecial) {
        this.busesSpecial = busesSpecial;
    }

    public String getTrams() {
        return trams;
    }

    public void setTrams(String trams) {
        this.trams = trams;
    }

    public String getTrolleybuses() {
        return trolleybuses;
    }

    public void setTrolleybuses(String trolleybuses) {
        this.trolleybuses = trolleybuses;
    }

    public String getMetros() {
        return metros;
    }

    public void setMetros(String metros) {
        this.metros = metros;
    }

    public String getInfotabloExists() {
        return infotabloExists;
    }

    public void setInfotabloExists(String infotabloExists) {
        this.infotabloExists = infotabloExists;
    }

    public Float getLatitude() {
        return latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    public Float getLongitude() {
        return longitude;
    }

    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

}
