package com.transportsmr.app.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STOP".
*/
public class StopDao extends AbstractDao<Stop, Long> {

    public static final String TABLENAME = "STOP";

    /**
     * Properties of entity Stop.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ks_id = new Property(1, String.class, "ks_id", false, "KS_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property AdjacentStreet = new Property(3, String.class, "adjacentStreet", false, "ADJACENT_STREET");
        public final static Property Direction = new Property(4, String.class, "direction", false, "DIRECTION");
        public final static Property Cluster = new Property(5, String.class, "cluster", false, "CLUSTER");
        public final static Property BusesMunicipal = new Property(6, String.class, "busesMunicipal", false, "BUSES_MUNICIPAL");
        public final static Property BusesCommercial = new Property(7, String.class, "busesCommercial", false, "BUSES_COMMERCIAL");
        public final static Property BusesPrigorod = new Property(8, String.class, "busesPrigorod", false, "BUSES_PRIGOROD");
        public final static Property BusesSeason = new Property(9, String.class, "busesSeason", false, "BUSES_SEASON");
        public final static Property BusesSpecial = new Property(10, String.class, "busesSpecial", false, "BUSES_SPECIAL");
        public final static Property Trams = new Property(11, String.class, "trams", false, "TRAMS");
        public final static Property Trolleybuses = new Property(12, String.class, "trolleybuses", false, "TROLLEYBUSES");
        public final static Property Metros = new Property(13, String.class, "metros", false, "METROS");
        public final static Property InfotabloExists = new Property(14, String.class, "infotabloExists", false, "INFOTABLO_EXISTS");
        public final static Property Latitude = new Property(15, Float.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(16, Float.class, "longitude", false, "LONGITUDE");
    }


    public StopDao(DaoConfig config) {
        super(config);
    }
    
    public StopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STOP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"KS_ID\" TEXT," + // 1: ks_id
                "\"TITLE\" TEXT," + // 2: title
                "\"ADJACENT_STREET\" TEXT," + // 3: adjacentStreet
                "\"DIRECTION\" TEXT," + // 4: direction
                "\"CLUSTER\" TEXT," + // 5: cluster
                "\"BUSES_MUNICIPAL\" TEXT," + // 6: busesMunicipal
                "\"BUSES_COMMERCIAL\" TEXT," + // 7: busesCommercial
                "\"BUSES_PRIGOROD\" TEXT," + // 8: busesPrigorod
                "\"BUSES_SEASON\" TEXT," + // 9: busesSeason
                "\"BUSES_SPECIAL\" TEXT," + // 10: busesSpecial
                "\"TRAMS\" TEXT," + // 11: trams
                "\"TROLLEYBUSES\" TEXT," + // 12: trolleybuses
                "\"METROS\" TEXT," + // 13: metros
                "\"INFOTABLO_EXISTS\" TEXT," + // 14: infotabloExists
                "\"LATITUDE\" REAL," + // 15: latitude
                "\"LONGITUDE\" REAL);"); // 16: longitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STOP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Stop entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ks_id = entity.getKs_id();
        if (ks_id != null) {
            stmt.bindString(2, ks_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String adjacentStreet = entity.getAdjacentStreet();
        if (adjacentStreet != null) {
            stmt.bindString(4, adjacentStreet);
        }
 
        String direction = entity.getDirection();
        if (direction != null) {
            stmt.bindString(5, direction);
        }
 
        String cluster = entity.getCluster();
        if (cluster != null) {
            stmt.bindString(6, cluster);
        }
 
        String busesMunicipal = entity.getBusesMunicipal();
        if (busesMunicipal != null) {
            stmt.bindString(7, busesMunicipal);
        }
 
        String busesCommercial = entity.getBusesCommercial();
        if (busesCommercial != null) {
            stmt.bindString(8, busesCommercial);
        }
 
        String busesPrigorod = entity.getBusesPrigorod();
        if (busesPrigorod != null) {
            stmt.bindString(9, busesPrigorod);
        }
 
        String busesSeason = entity.getBusesSeason();
        if (busesSeason != null) {
            stmt.bindString(10, busesSeason);
        }
 
        String busesSpecial = entity.getBusesSpecial();
        if (busesSpecial != null) {
            stmt.bindString(11, busesSpecial);
        }
 
        String trams = entity.getTrams();
        if (trams != null) {
            stmt.bindString(12, trams);
        }
 
        String trolleybuses = entity.getTrolleybuses();
        if (trolleybuses != null) {
            stmt.bindString(13, trolleybuses);
        }
 
        String metros = entity.getMetros();
        if (metros != null) {
            stmt.bindString(14, metros);
        }
 
        String infotabloExists = entity.getInfotabloExists();
        if (infotabloExists != null) {
            stmt.bindString(15, infotabloExists);
        }
 
        Float latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(16, latitude);
        }
 
        Float longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(17, longitude);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Stop entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ks_id = entity.getKs_id();
        if (ks_id != null) {
            stmt.bindString(2, ks_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String adjacentStreet = entity.getAdjacentStreet();
        if (adjacentStreet != null) {
            stmt.bindString(4, adjacentStreet);
        }
 
        String direction = entity.getDirection();
        if (direction != null) {
            stmt.bindString(5, direction);
        }
 
        String cluster = entity.getCluster();
        if (cluster != null) {
            stmt.bindString(6, cluster);
        }
 
        String busesMunicipal = entity.getBusesMunicipal();
        if (busesMunicipal != null) {
            stmt.bindString(7, busesMunicipal);
        }
 
        String busesCommercial = entity.getBusesCommercial();
        if (busesCommercial != null) {
            stmt.bindString(8, busesCommercial);
        }
 
        String busesPrigorod = entity.getBusesPrigorod();
        if (busesPrigorod != null) {
            stmt.bindString(9, busesPrigorod);
        }
 
        String busesSeason = entity.getBusesSeason();
        if (busesSeason != null) {
            stmt.bindString(10, busesSeason);
        }
 
        String busesSpecial = entity.getBusesSpecial();
        if (busesSpecial != null) {
            stmt.bindString(11, busesSpecial);
        }
 
        String trams = entity.getTrams();
        if (trams != null) {
            stmt.bindString(12, trams);
        }
 
        String trolleybuses = entity.getTrolleybuses();
        if (trolleybuses != null) {
            stmt.bindString(13, trolleybuses);
        }
 
        String metros = entity.getMetros();
        if (metros != null) {
            stmt.bindString(14, metros);
        }
 
        String infotabloExists = entity.getInfotabloExists();
        if (infotabloExists != null) {
            stmt.bindString(15, infotabloExists);
        }
 
        Float latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(16, latitude);
        }
 
        Float longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(17, longitude);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Stop readEntity(Cursor cursor, int offset) {
        Stop entity = new Stop( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ks_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // adjacentStreet
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // direction
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cluster
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // busesMunicipal
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // busesCommercial
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // busesPrigorod
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // busesSeason
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // busesSpecial
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // trams
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // trolleybuses
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // metros
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // infotabloExists
            cursor.isNull(offset + 15) ? null : cursor.getFloat(offset + 15), // latitude
            cursor.isNull(offset + 16) ? null : cursor.getFloat(offset + 16) // longitude
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Stop entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKs_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAdjacentStreet(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDirection(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCluster(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBusesMunicipal(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBusesCommercial(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBusesPrigorod(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBusesSeason(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBusesSpecial(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTrams(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTrolleybuses(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMetros(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setInfotabloExists(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setLatitude(cursor.isNull(offset + 15) ? null : cursor.getFloat(offset + 15));
        entity.setLongitude(cursor.isNull(offset + 16) ? null : cursor.getFloat(offset + 16));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Stop entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Stop entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Stop entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
